
	(function(){

		asterisk.route.currentPage.objects.icons = [
			{ n : 'fa-500px' , c : '\\f26e' },
			{ n : 'fa-address-book' , c : '\\f2b9' },
			{ n : 'fa-address-book-o' , c : '\\f2ba' },
			{ n : 'fa-address-card' , c : '\\f2bb' },
			{ n : 'fa-address-card-o' , c : '\\f2bc' },
			{ n : 'fa-adjust' , c : '\\f042' },
			{ n : 'fa-adn' , c : '\\f170' },
			{ n : 'fa-align-center' , c : '\\f037' },
			{ n : 'fa-align-justify' , c : '\\f039' },
			{ n : 'fa-align-left' , c : '\\f036' },
			{ n : 'fa-align-right' , c : '\\f038' },
			{ n : 'fa-amazon' , c : '\\f270' },
			{ n : 'fa-ambulance' , c : '\\f0f9' },
			{ n : 'fa-american-sign-language-interpreting' , c : '\\f2a3' },
			{ n : 'fa-anchor' , c : '\\f13d' },
			{ n : 'fa-android' , c : '\\f17b' },
			{ n : 'fa-angellist' , c : '\\f209' },
			{ n : 'fa-angle-double-down' , c : '\\f103' },
			{ n : 'fa-angle-double-left' , c : '\\f100' },
			{ n : 'fa-angle-double-right' , c : '\\f101' },
			{ n : 'fa-angle-double-up' , c : '\\f102' },
			{ n : 'fa-angle-down' , c : '\\f107' },
			{ n : 'fa-angle-left' , c : '\\f104' },
			{ n : 'fa-angle-right' , c : '\\f105' },
			{ n : 'fa-angle-up' , c : '\\f106' },
			{ n : 'fa-apple' , c : '\\f179' },
			{ n : 'fa-archive' , c : '\\f187' },
			{ n : 'fa-area-chart' , c : '\\f1fe' },
			{ n : 'fa-arrow-circle-down' , c : '\\f0ab' },
			{ n : 'fa-arrow-circle-left' , c : '\\f0a8' },
			{ n : 'fa-arrow-circle-o-down' , c : '\\f01a' },
			{ n : 'fa-arrow-circle-o-left' , c : '\\f190' },
			{ n : 'fa-arrow-circle-o-right' , c : '\\f18e' },
			{ n : 'fa-arrow-circle-o-up' , c : '\\f01b' },
			{ n : 'fa-arrow-circle-right' , c : '\\f0a9' },
			{ n : 'fa-arrow-circle-up' , c : '\\f0aa' },
			{ n : 'fa-arrow-down' , c : '\\f063' },
			{ n : 'fa-arrow-left' , c : '\\f060' },
			{ n : 'fa-arrow-right' , c : '\\f061' },
			{ n : 'fa-arrow-up' , c : '\\f062' },
			{ n : 'fa-arrows' , c : '\\f047' },
			{ n : 'fa-arrows-alt' , c : '\\f0b2' },
			{ n : 'fa-arrows-h' , c : '\\f07e' },
			{ n : 'fa-arrows-v' , c : '\\f07d' },
			{ n : 'fa-asl-interpreting' , c : '\\f2a3' },
			{ n : 'fa-assistive-listening-systems' , c : '\\f2a2' },
			{ n : 'fa-asterisk' , c : '\\f069' },
			{ n : 'fa-at' , c : '\\f1fa' },
			{ n : 'fa-audio-description' , c : '\\f29e' },
			{ n : 'fa-automobile' , c : '\\f1b9' },
			{ n : 'fa-backward' , c : '\\f04a' },
			{ n : 'fa-balance-scale' , c : '\\f24e' },
			{ n : 'fa-ban' , c : '\\f05e' },
			{ n : 'fa-bandcamp' , c : '\\f2d5' },
			{ n : 'fa-bank' , c : '\\f19c' },
			{ n : 'fa-bar-chart' , c : '\\f080' },
			{ n : 'fa-bar-chart-o' , c : '\\f080' },
			{ n : 'fa-barcode' , c : '\\f02a' },
			{ n : 'fa-bars' , c : '\\f0c9' },
			{ n : 'fa-bath' , c : '\\f2cd' },
			{ n : 'fa-bathtub' , c : '\\f2cd' },
			{ n : 'fa-battery' , c : '\\f240' },
			{ n : 'fa-battery-0' , c : '\\f244' },
			{ n : 'fa-battery-1' , c : '\\f243' },
			{ n : 'fa-battery-2' , c : '\\f242' },
			{ n : 'fa-battery-3' , c : '\\f241' },
			{ n : 'fa-battery-4' , c : '\\f240' },
			{ n : 'fa-battery-empty' , c : '\\f244' },
			{ n : 'fa-battery-full' , c : '\\f240' },
			{ n : 'fa-battery-half' , c : '\\f242' },
			{ n : 'fa-battery-quarter' , c : '\\f243' },
			{ n : 'fa-battery-three-quarters' , c : '\\f241' },
			{ n : 'fa-bed' , c : '\\f236' },
			{ n : 'fa-beer' , c : '\\f0fc' },
			{ n : 'fa-behance' , c : '\\f1b4' },
			{ n : 'fa-behance-square' , c : '\\f1b5' },
			{ n : 'fa-bell' , c : '\\f0f3' },
			{ n : 'fa-bell-o' , c : '\\f0a2' },
			{ n : 'fa-bell-slash' , c : '\\f1f6' },
			{ n : 'fa-bell-slash-o' , c : '\\f1f7' },
			{ n : 'fa-bicycle' , c : '\\f206' },
			{ n : 'fa-binoculars' , c : '\\f1e5' },
			{ n : 'fa-birthday-cake' , c : '\\f1fd' },
			{ n : 'fa-bitbucket' , c : '\\f171' },
			{ n : 'fa-bitbucket-square' , c : '\\f172' },
			{ n : 'fa-bitcoin' , c : '\\f15a' },
			{ n : 'fa-black-tie' , c : '\\f27e' },
			{ n : 'fa-blind' , c : '\\f29d' },
			{ n : 'fa-bluetooth' , c : '\\f293' },
			{ n : 'fa-bluetooth-b' , c : '\\f294' },
			{ n : 'fa-bold' , c : '\\f032' },
			{ n : 'fa-bolt' , c : '\\f0e7' },
			{ n : 'fa-bomb' , c : '\\f1e2' },
			{ n : 'fa-book' , c : '\\f02d' },
			{ n : 'fa-bookmark' , c : '\\f02e' },
			{ n : 'fa-bookmark-o' , c : '\\f097' },
			{ n : 'fa-braille' , c : '\\f2a1' },
			{ n : 'fa-briefcase' , c : '\\f0b1' },
			{ n : 'fa-btc' , c : '\\f15a' },
			{ n : 'fa-bug' , c : '\\f188' },
			{ n : 'fa-building' , c : '\\f1ad' },
			{ n : 'fa-building-o' , c : '\\f0f7' },
			{ n : 'fa-bullhorn' , c : '\\f0a1' },
			{ n : 'fa-bullseye' , c : '\\f140' },
			{ n : 'fa-bus' , c : '\\f207' },
			{ n : 'fa-buysellads' , c : '\\f20d' },
			{ n : 'fa-cab' , c : '\\f1ba' },
			{ n : 'fa-calculator' , c : '\\f1ec' },
			{ n : 'fa-calendar' , c : '\\f073' },
			{ n : 'fa-calendar-check-o' , c : '\\f274' },
			{ n : 'fa-calendar-minus-o' , c : '\\f272' },
			{ n : 'fa-calendar-o' , c : '\\f133' },
			{ n : 'fa-calendar-plus-o' , c : '\\f271' },
			{ n : 'fa-calendar-times-o' , c : '\\f273' },
			{ n : 'fa-camera' , c : '\\f030' },
			{ n : 'fa-camera-retro' , c : '\\f083' },
			{ n : 'fa-car' , c : '\\f1b9' },
			{ n : 'fa-caret-down' , c : '\\f0d7' },
			{ n : 'fa-caret-left' , c : '\\f0d9' },
			{ n : 'fa-caret-right' , c : '\\f0da' },
			{ n : 'fa-caret-square-o-down' , c : '\\f150' },
			{ n : 'fa-caret-square-o-left' , c : '\\f191' },
			{ n : 'fa-caret-square-o-right' , c : '\\f152' },
			{ n : 'fa-caret-square-o-up' , c : '\\f151' },
			{ n : 'fa-caret-up' , c : '\\f0d8' },
			{ n : 'fa-cart-arrow-down' , c : '\\f218' },
			{ n : 'fa-cart-plus' , c : '\\f217' },
			{ n : 'fa-cc' , c : '\\f20a' },
			{ n : 'fa-cc-amex' , c : '\\f1f3' },
			{ n : 'fa-cc-diners-club' , c : '\\f24c' },
			{ n : 'fa-cc-discover' , c : '\\f1f2' },
			{ n : 'fa-cc-jcb' , c : '\\f24b' },
			{ n : 'fa-cc-mastercard' , c : '\\f1f1' },
			{ n : 'fa-cc-paypal' , c : '\\f1f4' },
			{ n : 'fa-cc-stripe' , c : '\\f1f5' },
			{ n : 'fa-cc-visa' , c : '\\f1f0' },
			{ n : 'fa-certificate' , c : '\\f0a3' },
			{ n : 'fa-chain' , c : '\\f0c1' },
			{ n : 'fa-chain-broken' , c : '\\f127' },
			{ n : 'fa-check' , c : '\\f00c' },
			{ n : 'fa-check-circle' , c : '\\f058' },
			{ n : 'fa-check-circle-o' , c : '\\f05d' },
			{ n : 'fa-check-square' , c : '\\f14a' },
			{ n : 'fa-check-square-o' , c : '\\f046' },
			{ n : 'fa-chevron-circle-down' , c : '\\f13a' },
			{ n : 'fa-chevron-circle-left' , c : '\\f137' },
			{ n : 'fa-chevron-circle-right' , c : '\\f138' },
			{ n : 'fa-chevron-circle-up' , c : '\\f139' },
			{ n : 'fa-chevron-down' , c : '\\f078' },
			{ n : 'fa-chevron-left' , c : '\\f053' },
			{ n : 'fa-chevron-right' , c : '\\f054' },
			{ n : 'fa-chevron-up' , c : '\\f077' },
			{ n : 'fa-child' , c : '\\f1ae' },
			{ n : 'fa-chrome' , c : '\\f268' },
			{ n : 'fa-circle' , c : '\\f111' },
			{ n : 'fa-circle-o' , c : '\\f10c' },
			{ n : 'fa-circle-o-notch' , c : '\\f1ce' },
			{ n : 'fa-circle-thin' , c : '\\f1db' },
			{ n : 'fa-clipboard' , c : '\\f0ea' },
			{ n : 'fa-clock-o' , c : '\\f017' },
			{ n : 'fa-clone' , c : '\\f24d' },
			{ n : 'fa-close' , c : '\\f00d' },
			{ n : 'fa-cloud' , c : '\\f0c2' },
			{ n : 'fa-cloud-download' , c : '\\f0ed' },
			{ n : 'fa-cloud-upload' , c : '\\f0ee' },
			{ n : 'fa-cny' , c : '\\f157' },
			{ n : 'fa-code' , c : '\\f121' },
			{ n : 'fa-code-fork' , c : '\\f126' },
			{ n : 'fa-codepen' , c : '\\f1cb' },
			{ n : 'fa-codiepie' , c : '\\f284' },
			{ n : 'fa-coffee' , c : '\\f0f4' },
			{ n : 'fa-cog' , c : '\\f013' },
			{ n : 'fa-cogs' , c : '\\f085' },
			{ n : 'fa-columns' , c : '\\f0db' },
			{ n : 'fa-comment' , c : '\\f075' },
			{ n : 'fa-comment-o' , c : '\\f0e5' },
			{ n : 'fa-commenting' , c : '\\f27a' },
			{ n : 'fa-commenting-o' , c : '\\f27b' },
			{ n : 'fa-comments' , c : '\\f086' },
			{ n : 'fa-comments-o' , c : '\\f0e6' },
			{ n : 'fa-compass' , c : '\\f14e' },
			{ n : 'fa-compress' , c : '\\f066' },
			{ n : 'fa-connectdevelop' , c : '\\f20e' },
			{ n : 'fa-contao' , c : '\\f26d' },
			{ n : 'fa-copy' , c : '\\f0c5' },
			{ n : 'fa-copyright' , c : '\\f1f9' },
			{ n : 'fa-creative-commons' , c : '\\f25e' },
			{ n : 'fa-credit-card' , c : '\\f09d' },
			{ n : 'fa-credit-card-alt' , c : '\\f283' },
			{ n : 'fa-crop' , c : '\\f125' },
			{ n : 'fa-crosshairs' , c : '\\f05b' },
			{ n : 'fa-css3' , c : '\\f13c' },
			{ n : 'fa-cube' , c : '\\f1b2' },
			{ n : 'fa-cubes' , c : '\\f1b3' },
			{ n : 'fa-cut' , c : '\\f0c4' },
			{ n : 'fa-cutlery' , c : '\\f0f5' },
			{ n : 'fa-dashboard' , c : '\\f0e4' },
			{ n : 'fa-dashcube' , c : '\\f210' },
			{ n : 'fa-database' , c : '\\f1c0' },
			{ n : 'fa-deaf' , c : '\\f2a4' },
			{ n : 'fa-deafness' , c : '\\f2a4' },
			{ n : 'fa-dedent' , c : '\\f03b' },
			{ n : 'fa-delicious' , c : '\\f1a5' },
			{ n : 'fa-desktop' , c : '\\f108' },
			{ n : 'fa-deviantart' , c : '\\f1bd' },
			{ n : 'fa-diamond' , c : '\\f219' },
			{ n : 'fa-digg' , c : '\\f1a6' },
			{ n : 'fa-dollar' , c : '\\f155' },
			{ n : 'fa-dot-circle-o' , c : '\\f192' },
			{ n : 'fa-download' , c : '\\f019' },
			{ n : 'fa-dribbble' , c : '\\f17d' },
			{ n : 'fa-drivers-license' , c : '\\f2c2' },
			{ n : 'fa-drivers-license-o' , c : '\\f2c3' },
			{ n : 'fa-dropbox' , c : '\\f16b' },
			{ n : 'fa-drupal' , c : '\\f1a9' },
			{ n : 'fa-edge' , c : '\\f282' },
			{ n : 'fa-edit' , c : '\\f044' },
			{ n : 'fa-eercast' , c : '\\f2da' },
			{ n : 'fa-eject' , c : '\\f052' },
			{ n : 'fa-ellipsis-h' , c : '\\f141' },
			{ n : 'fa-ellipsis-v' , c : '\\f142' },
			{ n : 'fa-empire' , c : '\\f1d1' },
			{ n : 'fa-envelope' , c : '\\f0e0' },
			{ n : 'fa-envelope-o' , c : '\\f003' },
			{ n : 'fa-envelope-open' , c : '\\f2b6' },
			{ n : 'fa-envelope-open-o' , c : '\\f2b7' },
			{ n : 'fa-envelope-square' , c : '\\f199' },
			{ n : 'fa-envira' , c : '\\f299' },
			{ n : 'fa-eraser' , c : '\\f12d' },
			{ n : 'fa-etsy' , c : '\\f2d7' },
			{ n : 'fa-eur' , c : '\\f153' },
			{ n : 'fa-euro' , c : '\\f153' },
			{ n : 'fa-exchange' , c : '\\f0ec' },
			{ n : 'fa-exclamation' , c : '\\f12a' },
			{ n : 'fa-exclamation-circle' , c : '\\f06a' },
			{ n : 'fa-exclamation-triangle' , c : '\\f071' },
			{ n : 'fa-expand' , c : '\\f065' },
			{ n : 'fa-expeditedssl' , c : '\\f23e' },
			{ n : 'fa-external-link' , c : '\\f08e' },
			{ n : 'fa-external-link-square' , c : '\\f14c' },
			{ n : 'fa-eye' , c : '\\f06e' },
			{ n : 'fa-eye-slash' , c : '\\f070' },
			{ n : 'fa-eyedropper' , c : '\\f1fb' },
			{ n : 'fa-fa' , c : '\\f2b4' },
			{ n : 'fa-facebook' , c : '\\f09a' },
			{ n : 'fa-facebook-f' , c : '\\f09a' },
			{ n : 'fa-facebook-official' , c : '\\f230' },
			{ n : 'fa-facebook-square' , c : '\\f082' },
			{ n : 'fa-fast-backward' , c : '\\f049' },
			{ n : 'fa-fast-forward' , c : '\\f050' },
			{ n : 'fa-fax' , c : '\\f1ac' },
			{ n : 'fa-feed' , c : '\\f09e' },
			{ n : 'fa-female' , c : '\\f182' },
			{ n : 'fa-fighter-jet' , c : '\\f0fb' },
			{ n : 'fa-file' , c : '\\f15b' },
			{ n : 'fa-file-archive-o' , c : '\\f1c6' },
			{ n : 'fa-file-audio-o' , c : '\\f1c7' },
			{ n : 'fa-file-code-o' , c : '\\f1c9' },
			{ n : 'fa-file-excel-o' , c : '\\f1c3' },
			{ n : 'fa-file-image-o' , c : '\\f1c5' },
			{ n : 'fa-file-movie-o' , c : '\\f1c8' },
			{ n : 'fa-file-o' , c : '\\f016' },
			{ n : 'fa-file-pdf-o' , c : '\\f1c1' },
			{ n : 'fa-file-photo-o' , c : '\\f1c5' },
			{ n : 'fa-file-picture-o' , c : '\\f1c5' },
			{ n : 'fa-file-powerpoint-o' , c : '\\f1c4' },
			{ n : 'fa-file-sound-o' , c : '\\f1c7' },
			{ n : 'fa-file-text' , c : '\\f15c' },
			{ n : 'fa-file-text-o' , c : '\\f0f6' },
			{ n : 'fa-file-video-o' , c : '\\f1c8' },
			{ n : 'fa-file-word-o' , c : '\\f1c2' },
			{ n : 'fa-file-zip-o' , c : '\\f1c6' },
			{ n : 'fa-files-o' , c : '\\f0c5' },
			{ n : 'fa-film' , c : '\\f008' },
			{ n : 'fa-filter' , c : '\\f0b0' },
			{ n : 'fa-fire' , c : '\\f06d' },
			{ n : 'fa-fire-extinguisher' , c : '\\f134' },
			{ n : 'fa-firefox' , c : '\\f269' },
			{ n : 'fa-first-order' , c : '\\f2b0' },
			{ n : 'fa-flag' , c : '\\f024' },
			{ n : 'fa-flag-checkered' , c : '\\f11e' },
			{ n : 'fa-flag-o' , c : '\\f11d' },
			{ n : 'fa-flash' , c : '\\f0e7' },
			{ n : 'fa-flask' , c : '\\f0c3' },
			{ n : 'fa-flickr' , c : '\\f16e' },
			{ n : 'fa-floppy-o' , c : '\\f0c7' },
			{ n : 'fa-folder' , c : '\\f07b' },
			{ n : 'fa-folder-o' , c : '\\f114' },
			{ n : 'fa-folder-open' , c : '\\f07c' },
			{ n : 'fa-folder-open-o' , c : '\\f115' },
			{ n : 'fa-font' , c : '\\f031' },
			{ n : 'fa-font-awesome' , c : '\\f2b4' },
			{ n : 'fa-fonticons' , c : '\\f280' },
			{ n : 'fa-fort-awesome' , c : '\\f286' },
			{ n : 'fa-forumbee' , c : '\\f211' },
			{ n : 'fa-forward' , c : '\\f04e' },
			{ n : 'fa-foursquare' , c : '\\f180' },
			{ n : 'fa-free-code-camp' , c : '\\f2c5' },
			{ n : 'fa-frown-o' , c : '\\f119' },
			{ n : 'fa-futbol-o' , c : '\\f1e3' },
			{ n : 'fa-gamepad' , c : '\\f11b' },
			{ n : 'fa-gavel' , c : '\\f0e3' },
			{ n : 'fa-gbp' , c : '\\f154' },
			{ n : 'fa-ge' , c : '\\f1d1' },
			{ n : 'fa-gear' , c : '\\f013' },
			{ n : 'fa-gears' , c : '\\f085' },
			{ n : 'fa-genderless' , c : '\\f22d' },
			{ n : 'fa-get-pocket' , c : '\\f265' },
			{ n : 'fa-gg' , c : '\\f260' },
			{ n : 'fa-gg-circle' , c : '\\f261' },
			{ n : 'fa-gift' , c : '\\f06b' },
			{ n : 'fa-git' , c : '\\f1d3' },
			{ n : 'fa-git-square' , c : '\\f1d2' },
			{ n : 'fa-github' , c : '\\f09b' },
			{ n : 'fa-github-alt' , c : '\\f113' },
			{ n : 'fa-github-square' , c : '\\f092' },
			{ n : 'fa-gitlab' , c : '\\f296' },
			{ n : 'fa-gittip' , c : '\\f184' },
			{ n : 'fa-glass' , c : '\\f000' },
			{ n : 'fa-glide' , c : '\\f2a5' },
			{ n : 'fa-glide-g' , c : '\\f2a6' },
			{ n : 'fa-globe' , c : '\\f0ac' },
			{ n : 'fa-google' , c : '\\f1a0' },
			{ n : 'fa-google-plus' , c : '\\f0d5' },
			{ n : 'fa-google-plus-circle' , c : '\\f2b3' },
			{ n : 'fa-google-plus-official' , c : '\\f2b3' },
			{ n : 'fa-google-plus-square' , c : '\\f0d4' },
			{ n : 'fa-google-wallet' , c : '\\f1ee' },
			{ n : 'fa-graduation-cap' , c : '\\f19d' },
			{ n : 'fa-gratipay' , c : '\\f184' },
			{ n : 'fa-grav' , c : '\\f2d6' },
			{ n : 'fa-group' , c : '\\f0c0' },
			{ n : 'fa-h-square' , c : '\\f0fd' },
			{ n : 'fa-hacker-news' , c : '\\f1d4' },
			{ n : 'fa-hand-grab-o' , c : '\\f255' },
			{ n : 'fa-hand-lizard-o' , c : '\\f258' },
			{ n : 'fa-hand-o-down' , c : '\\f0a7' },
			{ n : 'fa-hand-o-left' , c : '\\f0a5' },
			{ n : 'fa-hand-o-right' , c : '\\f0a4' },
			{ n : 'fa-hand-o-up' , c : '\\f0a6' },
			{ n : 'fa-hand-paper-o' , c : '\\f256' },
			{ n : 'fa-hand-peace-o' , c : '\\f25b' },
			{ n : 'fa-hand-pointer-o' , c : '\\f25a' },
			{ n : 'fa-hand-rock-o' , c : '\\f255' },
			{ n : 'fa-hand-scissors-o' , c : '\\f257' },
			{ n : 'fa-hand-spock-o' , c : '\\f259' },
			{ n : 'fa-hand-stop-o' , c : '\\f256' },
			{ n : 'fa-handshake-o' , c : '\\f2b5' },
			{ n : 'fa-hard-of-hearing' , c : '\\f2a4' },
			{ n : 'fa-hashtag' , c : '\\f292' },
			{ n : 'fa-hdd-o' , c : '\\f0a0' },
			{ n : 'fa-header' , c : '\\f1dc' },
			{ n : 'fa-headphones' , c : '\\f025' },
			{ n : 'fa-heart' , c : '\\f004' },
			{ n : 'fa-heart-o' , c : '\\f08a' },
			{ n : 'fa-heartbeat' , c : '\\f21e' },
			{ n : 'fa-history' , c : '\\f1da' },
			{ n : 'fa-home' , c : '\\f015' },
			{ n : 'fa-hospital-o' , c : '\\f0f8' },
			{ n : 'fa-hotel' , c : '\\f236' },
			{ n : 'fa-hourglass' , c : '\\f254' },
			{ n : 'fa-hourglass-1' , c : '\\f251' },
			{ n : 'fa-hourglass-2' , c : '\\f252' },
			{ n : 'fa-hourglass-3' , c : '\\f253' },
			{ n : 'fa-hourglass-end' , c : '\\f253' },
			{ n : 'fa-hourglass-half' , c : '\\f252' },
			{ n : 'fa-hourglass-o' , c : '\\f250' },
			{ n : 'fa-hourglass-start' , c : '\\f251' },
			{ n : 'fa-houzz' , c : '\\f27c' },
			{ n : 'fa-html5' , c : '\\f13b' },
			{ n : 'fa-i-cursor' , c : '\\f246' },
			{ n : 'fa-id-badge' , c : '\\f2c1' },
			{ n : 'fa-id-card' , c : '\\f2c2' },
			{ n : 'fa-id-card-o' , c : '\\f2c3' },
			{ n : 'fa-ils' , c : '\\f20b' },
			{ n : 'fa-image' , c : '\\f03e' },
			{ n : 'fa-imdb' , c : '\\f2d8' },
			{ n : 'fa-inbox' , c : '\\f01c' },
			{ n : 'fa-indent' , c : '\\f03c' },
			{ n : 'fa-industry' , c : '\\f275' },
			{ n : 'fa-info' , c : '\\f129' },
			{ n : 'fa-info-circle' , c : '\\f05a' },
			{ n : 'fa-inr' , c : '\\f156' },
			{ n : 'fa-instagram' , c : '\\f16d' },
			{ n : 'fa-institution' , c : '\\f19c' },
			{ n : 'fa-internet-explorer' , c : '\\f26b' },
			{ n : 'fa-intersex' , c : '\\f224' },
			{ n : 'fa-ioxhost' , c : '\\f208' },
			{ n : 'fa-italic' , c : '\\f033' },
			{ n : 'fa-joomla' , c : '\\f1aa' },
			{ n : 'fa-jpy' , c : '\\f157' },
			{ n : 'fa-jsfiddle' , c : '\\f1cc' },
			{ n : 'fa-key' , c : '\\f084' },
			{ n : 'fa-keyboard-o' , c : '\\f11c' },
			{ n : 'fa-krw' , c : '\\f159' },
			{ n : 'fa-language' , c : '\\f1ab' },
			{ n : 'fa-laptop' , c : '\\f109' },
			{ n : 'fa-lastfm' , c : '\\f202' },
			{ n : 'fa-lastfm-square' , c : '\\f203' },
			{ n : 'fa-leaf' , c : '\\f06c' },
			{ n : 'fa-leanpub' , c : '\\f212' },
			{ n : 'fa-legal' , c : '\\f0e3' },
			{ n : 'fa-lemon-o' , c : '\\f094' },
			{ n : 'fa-level-down' , c : '\\f149' },
			{ n : 'fa-level-up' , c : '\\f148' },
			{ n : 'fa-life-bouy' , c : '\\f1cd' },
			{ n : 'fa-life-buoy' , c : '\\f1cd' },
			{ n : 'fa-life-ring' , c : '\\f1cd' },
			{ n : 'fa-life-saver' , c : '\\f1cd' },
			{ n : 'fa-lightbulb-o' , c : '\\f0eb' },
			{ n : 'fa-line-chart' , c : '\\f201' },
			{ n : 'fa-link' , c : '\\f0c1' },
			{ n : 'fa-linkedin' , c : '\\f0e1' },
			{ n : 'fa-linkedin-square' , c : '\\f08c' },
			{ n : 'fa-linode' , c : '\\f2b8' },
			{ n : 'fa-linux' , c : '\\f17c' },
			{ n : 'fa-list' , c : '\\f03a' },
			{ n : 'fa-list-alt' , c : '\\f022' },
			{ n : 'fa-list-ol' , c : '\\f0cb' },
			{ n : 'fa-list-ul' , c : '\\f0ca' },
			{ n : 'fa-location-arrow' , c : '\\f124' },
			{ n : 'fa-lock' , c : '\\f023' },
			{ n : 'fa-long-arrow-down' , c : '\\f175' },
			{ n : 'fa-long-arrow-left' , c : '\\f177' },
			{ n : 'fa-long-arrow-right' , c : '\\f178' },
			{ n : 'fa-long-arrow-up' , c : '\\f176' },
			{ n : 'fa-low-vision' , c : '\\f2a8' },
			{ n : 'fa-magic' , c : '\\f0d0' },
			{ n : 'fa-magnet' , c : '\\f076' },
			{ n : 'fa-mail-forward' , c : '\\f064' },
			{ n : 'fa-mail-reply' , c : '\\f112' },
			{ n : 'fa-mail-reply-all' , c : '\\f122' },
			{ n : 'fa-male' , c : '\\f183' },
			{ n : 'fa-map' , c : '\\f279' },
			{ n : 'fa-map-marker' , c : '\\f041' },
			{ n : 'fa-map-o' , c : '\\f278' },
			{ n : 'fa-map-pin' , c : '\\f276' },
			{ n : 'fa-map-signs' , c : '\\f277' },
			{ n : 'fa-mars' , c : '\\f222' },
			{ n : 'fa-mars-double' , c : '\\f227' },
			{ n : 'fa-mars-stroke' , c : '\\f229' },
			{ n : 'fa-mars-stroke-h' , c : '\\f22b' },
			{ n : 'fa-mars-stroke-v' , c : '\\f22a' },
			{ n : 'fa-maxcdn' , c : '\\f136' },
			{ n : 'fa-meanpath' , c : '\\f20c' },
			{ n : 'fa-medium' , c : '\\f23a' },
			{ n : 'fa-medkit' , c : '\\f0fa' },
			{ n : 'fa-meetup' , c : '\\f2e0' },
			{ n : 'fa-meh-o' , c : '\\f11a' },
			{ n : 'fa-mercury' , c : '\\f223' },
			{ n : 'fa-microchip' , c : '\\f2db' },
			{ n : 'fa-microphone' , c : '\\f130' },
			{ n : 'fa-microphone-slash' , c : '\\f131' },
			{ n : 'fa-minus' , c : '\\f068' },
			{ n : 'fa-minus-circle' , c : '\\f056' },
			{ n : 'fa-minus-square' , c : '\\f146' },
			{ n : 'fa-minus-square-o' , c : '\\f147' },
			{ n : 'fa-mixcloud' , c : '\\f289' },
			{ n : 'fa-mobile' , c : '\\f10b' },
			{ n : 'fa-mobile-phone' , c : '\\f10b' },
			{ n : 'fa-modx' , c : '\\f285' },
			{ n : 'fa-money' , c : '\\f0d6' },
			{ n : 'fa-moon-o' , c : '\\f186' },
			{ n : 'fa-mortar-board' , c : '\\f19d' },
			{ n : 'fa-motorcycle' , c : '\\f21c' },
			{ n : 'fa-mouse-pointer' , c : '\\f245' },
			{ n : 'fa-music' , c : '\\f001' },
			{ n : 'fa-navicon' , c : '\\f0c9' },
			{ n : 'fa-neuter' , c : '\\f22c' },
			{ n : 'fa-newspaper-o' , c : '\\f1ea' },
			{ n : 'fa-object-group' , c : '\\f247' },
			{ n : 'fa-object-ungroup' , c : '\\f248' },
			{ n : 'fa-odnoklassniki' , c : '\\f263' },
			{ n : 'fa-odnoklassniki-square' , c : '\\f264' },
			{ n : 'fa-opencart' , c : '\\f23d' },
			{ n : 'fa-openid' , c : '\\f19b' },
			{ n : 'fa-opera' , c : '\\f26a' },
			{ n : 'fa-optin-monster' , c : '\\f23c' },
			{ n : 'fa-outdent' , c : '\\f03b' },
			{ n : 'fa-pagelines' , c : '\\f18c' },
			{ n : 'fa-paint-brush' , c : '\\f1fc' },
			{ n : 'fa-paper-plane' , c : '\\f1d8' },
			{ n : 'fa-paper-plane-o' , c : '\\f1d9' },
			{ n : 'fa-paperclip' , c : '\\f0c6' },
			{ n : 'fa-paragraph' , c : '\\f1dd' },
			{ n : 'fa-paste' , c : '\\f0ea' },
			{ n : 'fa-pause' , c : '\\f04c' },
			{ n : 'fa-pause-circle' , c : '\\f28b' },
			{ n : 'fa-pause-circle-o' , c : '\\f28c' },
			{ n : 'fa-paw' , c : '\\f1b0' },
			{ n : 'fa-paypal' , c : '\\f1ed' },
			{ n : 'fa-pencil' , c : '\\f040' },
			{ n : 'fa-pencil-square' , c : '\\f14b' },
			{ n : 'fa-pencil-square-o' , c : '\\f044' },
			{ n : 'fa-percent' , c : '\\f295' },
			{ n : 'fa-phone' , c : '\\f095' },
			{ n : 'fa-phone-square' , c : '\\f098' },
			{ n : 'fa-photo' , c : '\\f03e' },
			{ n : 'fa-picture-o' , c : '\\f03e' },
			{ n : 'fa-pie-chart' , c : '\\f200' },
			{ n : 'fa-pied-piper' , c : '\\f2ae' },
			{ n : 'fa-pied-piper-alt' , c : '\\f1a8' },
			{ n : 'fa-pied-piper-pp' , c : '\\f1a7' },
			{ n : 'fa-pinterest' , c : '\\f0d2' },
			{ n : 'fa-pinterest-p' , c : '\\f231' },
			{ n : 'fa-pinterest-square' , c : '\\f0d3' },
			{ n : 'fa-plane' , c : '\\f072' },
			{ n : 'fa-play' , c : '\\f04b' },
			{ n : 'fa-play-circle' , c : '\\f144' },
			{ n : 'fa-play-circle-o' , c : '\\f01d' },
			{ n : 'fa-plug' , c : '\\f1e6' },
			{ n : 'fa-plus' , c : '\\f067' },
			{ n : 'fa-plus-circle' , c : '\\f055' },
			{ n : 'fa-plus-square' , c : '\\f0fe' },
			{ n : 'fa-plus-square-o' , c : '\\f196' },
			{ n : 'fa-podcast' , c : '\\f2ce' },
			{ n : 'fa-power-off' , c : '\\f011' },
			{ n : 'fa-print' , c : '\\f02f' },
			{ n : 'fa-product-hunt' , c : '\\f288' },
			{ n : 'fa-puzzle-piece' , c : '\\f12e' },
			{ n : 'fa-qq' , c : '\\f1d6' },
			{ n : 'fa-qrcode' , c : '\\f029' },
			{ n : 'fa-question' , c : '\\f128' },
			{ n : 'fa-question-circle' , c : '\\f059' },
			{ n : 'fa-question-circle-o' , c : '\\f29c' },
			{ n : 'fa-quora' , c : '\\f2c4' },
			{ n : 'fa-quote-left' , c : '\\f10d' },
			{ n : 'fa-quote-right' , c : '\\f10e' },
			{ n : 'fa-ra' , c : '\\f1d0' },
			{ n : 'fa-random' , c : '\\f074' },
			{ n : 'fa-ravelry' , c : '\\f2d9' },
			{ n : 'fa-rebel' , c : '\\f1d0' },
			{ n : 'fa-recycle' , c : '\\f1b8' },
			{ n : 'fa-reddit' , c : '\\f1a1' },
			{ n : 'fa-reddit-alien' , c : '\\f281' },
			{ n : 'fa-reddit-square' , c : '\\f1a2' },
			{ n : 'fa-refresh' , c : '\\f021' },
			{ n : 'fa-registered' , c : '\\f25d' },
			{ n : 'fa-remove' , c : '\\f00d' },
			{ n : 'fa-renren' , c : '\\f18b' },
			{ n : 'fa-reorder' , c : '\\f0c9' },
			{ n : 'fa-repeat' , c : '\\f01e' },
			{ n : 'fa-reply' , c : '\\f112' },
			{ n : 'fa-reply-all' , c : '\\f122' },
			{ n : 'fa-resistance' , c : '\\f1d0' },
			{ n : 'fa-retweet' , c : '\\f079' },
			{ n : 'fa-rmb' , c : '\\f157' },
			{ n : 'fa-road' , c : '\\f018' },
			{ n : 'fa-rocket' , c : '\\f135' },
			{ n : 'fa-rotate-left' , c : '\\f0e2' },
			{ n : 'fa-rotate-right' , c : '\\f01e' },
			{ n : 'fa-rouble' , c : '\\f158' },
			{ n : 'fa-rss' , c : '\\f09e' },
			{ n : 'fa-rss-square' , c : '\\f143' },
			{ n : 'fa-rub' , c : '\\f158' },
			{ n : 'fa-ruble' , c : '\\f158' },
			{ n : 'fa-rupee' , c : '\\f156' },
			{ n : 'fa-s15' , c : '\\f2cd' },
			{ n : 'fa-safari' , c : '\\f267' },
			{ n : 'fa-save' , c : '\\f0c7' },
			{ n : 'fa-scissors' , c : '\\f0c4' },
			{ n : 'fa-scribd' , c : '\\f28a' },
			{ n : 'fa-search' , c : '\\f002' },
			{ n : 'fa-search-minus' , c : '\\f010' },
			{ n : 'fa-search-plus' , c : '\\f00e' },
			{ n : 'fa-sellsy' , c : '\\f213' },
			{ n : 'fa-send' , c : '\\f1d8' },
			{ n : 'fa-send-o' , c : '\\f1d9' },
			{ n : 'fa-server' , c : '\\f233' },
			{ n : 'fa-share' , c : '\\f064' },
			{ n : 'fa-share-alt' , c : '\\f1e0' },
			{ n : 'fa-share-alt-square' , c : '\\f1e1' },
			{ n : 'fa-share-square' , c : '\\f14d' },
			{ n : 'fa-share-square-o' , c : '\\f045' },
			{ n : 'fa-shekel' , c : '\\f20b' },
			{ n : 'fa-sheqel' , c : '\\f20b' },
			{ n : 'fa-shield' , c : '\\f132' },
			{ n : 'fa-ship' , c : '\\f21a' },
			{ n : 'fa-shirtsinbulk' , c : '\\f214' },
			{ n : 'fa-shopping-bag' , c : '\\f290' },
			{ n : 'fa-shopping-basket' , c : '\\f291' },
			{ n : 'fa-shopping-cart' , c : '\\f07a' },
			{ n : 'fa-shower' , c : '\\f2cc' },
			{ n : 'fa-sign-in' , c : '\\f090' },
			{ n : 'fa-sign-language' , c : '\\f2a7' },
			{ n : 'fa-sign-out' , c : '\\f08b' },
			{ n : 'fa-signal' , c : '\\f012' },
			{ n : 'fa-signing' , c : '\\f2a7' },
			{ n : 'fa-simplybuilt' , c : '\\f215' },
			{ n : 'fa-sitemap' , c : '\\f0e8' },
			{ n : 'fa-skyatlas' , c : '\\f216' },
			{ n : 'fa-skype' , c : '\\f17e' },
			{ n : 'fa-slack' , c : '\\f198' },
			{ n : 'fa-sliders' , c : '\\f1de' },
			{ n : 'fa-slideshare' , c : '\\f1e7' },
			{ n : 'fa-smile-o' , c : '\\f118' },
			{ n : 'fa-snapchat' , c : '\\f2ab' },
			{ n : 'fa-snapchat-ghost' , c : '\\f2ac' },
			{ n : 'fa-snapchat-square' , c : '\\f2ad' },
			{ n : 'fa-snowflake-o' , c : '\\f2dc' },
			{ n : 'fa-soccer-ball-o' , c : '\\f1e3' },
			{ n : 'fa-sort' , c : '\\f0dc' },
			{ n : 'fa-sort-alpha-asc' , c : '\\f15d' },
			{ n : 'fa-sort-alpha-desc' , c : '\\f15e' },
			{ n : 'fa-sort-amount-asc' , c : '\\f160' },
			{ n : 'fa-sort-amount-desc' , c : '\\f161' },
			{ n : 'fa-sort-asc' , c : '\\f0de' },
			{ n : 'fa-sort-desc' , c : '\\f0dd' },
			{ n : 'fa-sort-down' , c : '\\f0dd' },
			{ n : 'fa-sort-numeric-asc' , c : '\\f162' },
			{ n : 'fa-sort-numeric-desc' , c : '\\f163' },
			{ n : 'fa-sort-up' , c : '\\f0de' },
			{ n : 'fa-soundcloud' , c : '\\f1be' },
			{ n : 'fa-space-shuttle' , c : '\\f197' },
			{ n : 'fa-spinner' , c : '\\f110' },
			{ n : 'fa-spoon' , c : '\\f1b1' },
			{ n : 'fa-spotify' , c : '\\f1bc' },
			{ n : 'fa-square' , c : '\\f0c8' },
			{ n : 'fa-square-o' , c : '\\f096' },
			{ n : 'fa-stack-exchange' , c : '\\f18d' },
			{ n : 'fa-stack-overflow' , c : '\\f16c' },
			{ n : 'fa-star' , c : '\\f005' },
			{ n : 'fa-star-half' , c : '\\f089' },
			{ n : 'fa-star-half-empty' , c : '\\f123' },
			{ n : 'fa-star-half-full' , c : '\\f123' },
			{ n : 'fa-star-half-o' , c : '\\f123' },
			{ n : 'fa-star-o' , c : '\\f006' },
			{ n : 'fa-steam' , c : '\\f1b6' },
			{ n : 'fa-steam-square' , c : '\\f1b7' },
			{ n : 'fa-step-backward' , c : '\\f048' },
			{ n : 'fa-step-forward' , c : '\\f051' },
			{ n : 'fa-stethoscope' , c : '\\f0f1' },
			{ n : 'fa-sticky-note' , c : '\\f249' },
			{ n : 'fa-sticky-note-o' , c : '\\f24a' },
			{ n : 'fa-stop' , c : '\\f04d' },
			{ n : 'fa-stop-circle' , c : '\\f28d' },
			{ n : 'fa-stop-circle-o' , c : '\\f28e' },
			{ n : 'fa-street-view' , c : '\\f21d' },
			{ n : 'fa-strikethrough' , c : '\\f0cc' },
			{ n : 'fa-stumbleupon' , c : '\\f1a4' },
			{ n : 'fa-stumbleupon-circle' , c : '\\f1a3' },
			{ n : 'fa-subscript' , c : '\\f12c' },
			{ n : 'fa-subway' , c : '\\f239' },
			{ n : 'fa-suitcase' , c : '\\f0f2' },
			{ n : 'fa-sun-o' , c : '\\f185' },
			{ n : 'fa-superpowers' , c : '\\f2dd' },
			{ n : 'fa-superscript' , c : '\\f12b' },
			{ n : 'fa-support' , c : '\\f1cd' },
			{ n : 'fa-table' , c : '\\f0ce' },
			{ n : 'fa-tablet' , c : '\\f10a' },
			{ n : 'fa-tachometer' , c : '\\f0e4' },
			{ n : 'fa-tag' , c : '\\f02b' },
			{ n : 'fa-tags' , c : '\\f02c' },
			{ n : 'fa-tasks' , c : '\\f0ae' },
			{ n : 'fa-taxi' , c : '\\f1ba' },
			{ n : 'fa-telegram' , c : '\\f2c6' },
			{ n : 'fa-television' , c : '\\f26c' },
			{ n : 'fa-tencent-weibo' , c : '\\f1d5' },
			{ n : 'fa-terminal' , c : '\\f120' },
			{ n : 'fa-text-height' , c : '\\f034' },
			{ n : 'fa-text-width' , c : '\\f035' },
			{ n : 'fa-th' , c : '\\f00a' },
			{ n : 'fa-th-large' , c : '\\f009' },
			{ n : 'fa-th-list' , c : '\\f00b' },
			{ n : 'fa-themeisle' , c : '\\f2b2' },
			{ n : 'fa-thermometer' , c : '\\f2c7' },
			{ n : 'fa-thermometer-0' , c : '\\f2cb' },
			{ n : 'fa-thermometer-1' , c : '\\f2ca' },
			{ n : 'fa-thermometer-2' , c : '\\f2c9' },
			{ n : 'fa-thermometer-3' , c : '\\f2c8' },
			{ n : 'fa-thermometer-4' , c : '\\f2c7' },
			{ n : 'fa-thermometer-empty' , c : '\\f2cb' },
			{ n : 'fa-thermometer-full' , c : '\\f2c7' },
			{ n : 'fa-thermometer-half' , c : '\\f2c9' },
			{ n : 'fa-thermometer-quarter' , c : '\\f2ca' },
			{ n : 'fa-thermometer-three-quarters' , c : '\\f2c8' },
			{ n : 'fa-thumb-tack' , c : '\\f08d' },
			{ n : 'fa-thumbs-down' , c : '\\f165' },
			{ n : 'fa-thumbs-o-down' , c : '\\f088' },
			{ n : 'fa-thumbs-o-up' , c : '\\f087' },
			{ n : 'fa-thumbs-up' , c : '\\f164' },
			{ n : 'fa-ticket' , c : '\\f145' },
			{ n : 'fa-times' , c : '\\f00d' },
			{ n : 'fa-times-circle' , c : '\\f057' },
			{ n : 'fa-times-circle-o' , c : '\\f05c' },
			{ n : 'fa-times-rectangle' , c : '\\f2d3' },
			{ n : 'fa-times-rectangle-o' , c : '\\f2d4' },
			{ n : 'fa-tint' , c : '\\f043' },
			{ n : 'fa-toggle-down' , c : '\\f150' },
			{ n : 'fa-toggle-left' , c : '\\f191' },
			{ n : 'fa-toggle-off' , c : '\\f204' },
			{ n : 'fa-toggle-on' , c : '\\f205' },
			{ n : 'fa-toggle-right' , c : '\\f152' },
			{ n : 'fa-toggle-up' , c : '\\f151' },
			{ n : 'fa-trademark' , c : '\\f25c' },
			{ n : 'fa-train' , c : '\\f238' },
			{ n : 'fa-transgender' , c : '\\f224' },
			{ n : 'fa-transgender-alt' , c : '\\f225' },
			{ n : 'fa-trash' , c : '\\f1f8' },
			{ n : 'fa-trash-o' , c : '\\f014' },
			{ n : 'fa-tree' , c : '\\f1bb' },
			{ n : 'fa-trello' , c : '\\f181' },
			{ n : 'fa-tripadvisor' , c : '\\f262' },
			{ n : 'fa-trophy' , c : '\\f091' },
			{ n : 'fa-truck' , c : '\\f0d1' },
			{ n : 'fa-try' , c : '\\f195' },
			{ n : 'fa-tty' , c : '\\f1e4' },
			{ n : 'fa-tumblr' , c : '\\f173' },
			{ n : 'fa-tumblr-square' , c : '\\f174' },
			{ n : 'fa-turkish-lira' , c : '\\f195' },
			{ n : 'fa-tv' , c : '\\f26c' },
			{ n : 'fa-twitch' , c : '\\f1e8' },
			{ n : 'fa-twitter' , c : '\\f099' },
			{ n : 'fa-twitter-square' , c : '\\f081' },
			{ n : 'fa-umbrella' , c : '\\f0e9' },
			{ n : 'fa-underline' , c : '\\f0cd' },
			{ n : 'fa-undo' , c : '\\f0e2' },
			{ n : 'fa-universal-access' , c : '\\f29a' },
			{ n : 'fa-university' , c : '\\f19c' },
			{ n : 'fa-unlink' , c : '\\f127' },
			{ n : 'fa-unlock' , c : '\\f09c' },
			{ n : 'fa-unlock-alt' , c : '\\f13e' },
			{ n : 'fa-unsorted' , c : '\\f0dc' },
			{ n : 'fa-upload' , c : '\\f093' },
			{ n : 'fa-usb' , c : '\\f287' },
			{ n : 'fa-usd' , c : '\\f155' },
			{ n : 'fa-user' , c : '\\f007' },
			{ n : 'fa-user-circle' , c : '\\f2bd' },
			{ n : 'fa-user-circle-o' , c : '\\f2be' },
			{ n : 'fa-user-md' , c : '\\f0f0' },
			{ n : 'fa-user-o' , c : '\\f2c0' },
			{ n : 'fa-user-plus' , c : '\\f234' },
			{ n : 'fa-user-secret' , c : '\\f21b' },
			{ n : 'fa-user-times' , c : '\\f235' },
			{ n : 'fa-users' , c : '\\f0c0' },
			{ n : 'fa-vcard' , c : '\\f2bb' },
			{ n : 'fa-vcard-o' , c : '\\f2bc' },
			{ n : 'fa-venus' , c : '\\f221' },
			{ n : 'fa-venus-double' , c : '\\f226' },
			{ n : 'fa-venus-mars' , c : '\\f228' },
			{ n : 'fa-viacoin' , c : '\\f237' },
			{ n : 'fa-viadeo' , c : '\\f2a9' },
			{ n : 'fa-viadeo-square' , c : '\\f2aa' },
			{ n : 'fa-video-camera' , c : '\\f03d' },
			{ n : 'fa-vimeo' , c : '\\f27d' },
			{ n : 'fa-vimeo-square' , c : '\\f194' },
			{ n : 'fa-vine' , c : '\\f1ca' },
			{ n : 'fa-vk' , c : '\\f189' },
			{ n : 'fa-volume-control-phone' , c : '\\f2a0' },
			{ n : 'fa-volume-down' , c : '\\f027' },
			{ n : 'fa-volume-off' , c : '\\f026' },
			{ n : 'fa-volume-up' , c : '\\f028' },
			{ n : 'fa-warning' , c : '\\f071' },
			{ n : 'fa-wechat' , c : '\\f1d7' },
			{ n : 'fa-weibo' , c : '\\f18a' },
			{ n : 'fa-weixin' , c : '\\f1d7' },
			{ n : 'fa-whatsapp' , c : '\\f232' },
			{ n : 'fa-wheelchair' , c : '\\f193' },
			{ n : 'fa-wheelchair-alt' , c : '\\f29b' },
			{ n : 'fa-wifi' , c : '\\f1eb' },
			{ n : 'fa-wikipedia-w' , c : '\\f266' },
			{ n : 'fa-window-close' , c : '\\f2d3' },
			{ n : 'fa-window-close-o' , c : '\\f2d4' },
			{ n : 'fa-window-maximize' , c : '\\f2d0' },
			{ n : 'fa-window-minimize' , c : '\\f2d1' },
			{ n : 'fa-window-restore' , c : '\\f2d2' },
			{ n : 'fa-windows' , c : '\\f17a' },
			{ n : 'fa-won' , c : '\\f159' },
			{ n : 'fa-wordpress' , c : '\\f19a' },
			{ n : 'fa-wpbeginner' , c : '\\f297' },
			{ n : 'fa-wpexplorer' , c : '\\f2de' },
			{ n : 'fa-wpforms' , c : '\\f298' },
			{ n : 'fa-wrench' , c : '\\f0ad' },
			{ n : 'fa-xing' , c : '\\f168' },
			{ n : 'fa-xing-square' , c : '\\f169' },
			{ n : 'fa-y-combinator' , c : '\\f23b' },
			{ n : 'fa-y-combinator-square' , c : '\\f1d4' },
			{ n : 'fa-yahoo' , c : '\\f19e' },
			{ n : 'fa-yc' , c : '\\f23b' },
			{ n : 'fa-yc-square' , c : '\\f1d4' },
			{ n : 'fa-yelp' , c : '\\f1e9' },
			{ n : 'fa-yen' , c : '\\f157' },
			{ n : 'fa-yoast' , c : '\\f2b1' },
			{ n : 'fa-youtube' , c : '\\f167' },
			{ n : 'fa-youtube-play' , c : '\\f16a' },
			{ n : 'fa-youtube-square' , c : '\\f166' },
		];

		asterisk.route.currentPage.objects.itemsToGenerate = [];

		// generateItem() 
		// --------------------------------
			// -- generate each individual Element's HTML markup
			// -- used within loadNextItems()

			asterisk.route.currentPage.functions.generateItem = function(item) {
				var newItem = document.createElement('div');
				newItem.classList = 'fa-itemContainer';
				newItem.setAttribute('data-itemClass', item.n);
				newItem.innerHTML = 
					'<div class="col-2 sm-col-3 py-sm px-0"> '												+
						'<div class="col-4 xs-hidden 	text-center 			fa '+item.n+'"> </div> '	+
						'<div class="col-4 xs-hidden 	text-center xfa-text-md fa '+item.n+'"> </div> '	+
						'<div class="col-4 				text-center xfa-text-lg fa '+item.n+'"> </div> '	+
					'</div> '																				+
					'<div class="col-7 sm-col-6"> <div class="fa-itemContainer-classDiv">'+item.n+'</div> </div> '	+
					'<div class="col-3 sm-col-3"> <div class="fa-itemContainer-valueDiv">'+item.c+'</div> </div> '	;
					
				return newItem;
			};

		// loadNextItems() 
		// --------------------------------
			// -- generate the next series of search results 
			// -- used within checkIconListScrolls() -- if over 50 remaining, will run when user scrolls to the bottom of page

			asterisk.route.currentPage.functions.loadNextItems = function() {

				var loadingBottom = document.getElementById('loading-bottom');

				var newDocFragment = document.createDocumentFragment();

				loadingBottom.classList.remove('hidden');
				var itemsToGenerate = asterisk.route.currentPage.objects.itemsToGenerate;
				var itemsToGenerate_current;

				if (itemsToGenerate.length > 50) {
					itemsToGenerate_current = itemsToGenerate.slice(0, 49);
					asterisk.route.currentPage.objects.itemsToGenerate = itemsToGenerate.slice(50);
				} else {
					itemsToGenerate_current = itemsToGenerate;
					asterisk.route.currentPage.objects.itemsToGenerate = [];
					loadingBottom.classList.add('hidden');
				};
					
				itemsToGenerate_current.map(function(item) {
					newDocFragment.appendChild( asterisk.route.currentPage.functions.generateItem(item) )
				});

				document.getElementById('faSearch--resultsContainer').appendChild(newDocFragment);
			};

		// checkIconListScroll() 
		// --------------------------------
			// -- checks if the user has scrolled to the bottom of the page 
			// -- if (scrolledToBottom && itemsToLoad) >> loadNextItems()

			asterisk.route.currentPage.functions.checkIconListScroll = function() {

				if (document.documentElement.scrollTop + window.innerHeight > document.documentElement.scrollHeight - 20) {
					asterisk.route.currentPage.functions.loadNextItems()
				};

				if (
					(asterisk.route.currentPage.objects.itemsToGenerate.length > 0) && 
					(window.location.href.toLowerCase().indexOf('fontAwesomeIconList.html'.toLowerCase()) > -1) 
				) { 
					setTimeout(function(){
						var checkIconListScroll = asterisk.route.currentPage.functions.checkIconListScroll;
						if (checkIconListScroll) { checkIconListScroll() }
					} , 500) 
				};
			};

		// runOnInput() 
		// --------------------------------
			// -- used within eventHandlers.byandu_faIconList__onInput()

			asterisk.route.currentPage.functions.runOnInput = function(current_input) {

				var resultsContainer = document.getElementById('faSearch--resultsContainer');
				resultsContainer.classList.add('faSpinner', 'faSpinner-fast');
				resultsContainer.innerHTML = ''; 

				asterisk.route.currentPage.objects.itemsToGenerate = asterisk.route.currentPage.objects.icons.filter(item => item.n.indexOf(current_input) > -1);

				if (asterisk.route.currentPage.objects.itemsToGenerate.length > 0) { 
					asterisk.route.currentPage.functions.loadNextItems();
					asterisk.route.currentPage.functions.checkIconListScroll();
					document.getElementById('noResults').classList.add('hidden');
				} else { 
					document.getElementById('noResults').classList.remove('hidden') 
				};

				window.scrollTo(0,0);

				setTimeout(function(){ 
					document.getElementById('faSearch--resultsContainer').classList.remove('faSpinner', 'faSpinner-fast') 
				}, 33);
			};

		// eventHandlers
		// --------------------------------

			// runOnInput() 
			// --------------------------------

				asterisk.route.currentPage.eventHandlers.byandu_faIconList__onInput = function(e) {
					var current_input = e.target.value.toLowerCase();
					if (current_input == '') { current_input = 'a' };

					asterisk.route.currentPage.functions.runOnInput(current_input);
				};

				asterisk.route.currentPage.addEvent(
					document.getElementById('faSearch--input') , 
					'input' , 
					asterisk.route.currentPage.eventHandlers.byandu_faIconList__onInput
				);

			// byandu_faIconList__resultClick() 
			// --------------------------------

				asterisk.route.currentPage.eventHandlers.byandu_faIconList__resultClick = function(e) {

					var current_target = e.target;

					if (hasClass(current_target, 'fa-itemContainer-classDiv') 
					||  hasClass(current_target, 'fa-itemContainer-valueDiv')) {

						copyText(current_target);
						current_target.classList.add('text-copied');
						setTimeout(function(){ current_target.classList.remove('text-copied')}, 800)

					}
				};

				asterisk.route.currentPage.addEvent(
					document.getElementById('faSearch--resultsContainer') , 
					'click' , 
					asterisk.route.currentPage.eventHandlers.byandu_faIconList__resultClick
				);

		// run initial check to populate the list 
		// --------------------------------

			asterisk.route.currentPage.functions.runOnInput('a');

	})();